"""Tests for CognitionEngine._safe_parse_tool_args — the state-machine parser."""

import pytest
from unittest.mock import MagicMock, AsyncMock


@pytest.fixture
def engine():
    """Create a CognitionEngine with minimal mocks."""
    from src.engines.cognition import CognitionEngine
    bot = MagicMock()
    bot.engine_manager = MagicMock()
    bot.cerebrum = MagicMock()
    ce = CognitionEngine(bot)
    return ce


class TestSafeParseToolArgs:
    """Test the state-machine tool argument parser."""

    # ── Basic cases ─────────────────────────────────────────────

    def test_empty_string(self, engine):
        assert engine._safe_parse_tool_args("") == {}

    def test_none_input(self, engine):
        assert engine._safe_parse_tool_args(None) == {}

    def test_whitespace_only(self, engine):
        assert engine._safe_parse_tool_args("   ") == {}

    def test_simple_string_arg(self, engine):
        result = engine._safe_parse_tool_args('query="hello world"')
        assert result == {"query": "hello world"}

    def test_simple_single_quotes(self, engine):
        result = engine._safe_parse_tool_args("query='hello world'")
        assert result == {"query": "hello world"}

    def test_multiple_args(self, engine):
        result = engine._safe_parse_tool_args('action="add", description="Fix bug"')
        assert result == {"action": "add", "description": "Fix bug"}

    def test_integer_arg(self, engine):
        result = engine._safe_parse_tool_args('start_line=1, limit=50')
        assert result == {"start_line": 1, "limit": 50}

    def test_float_arg(self, engine):
        result = engine._safe_parse_tool_args('threshold=0.85')
        assert result == {"threshold": 0.85}

    def test_boolean_true(self, engine):
        result = engine._safe_parse_tool_args('verbose=True')
        assert result == {"verbose": True}

    def test_boolean_false(self, engine):
        result = engine._safe_parse_tool_args('dry_run=False')
        assert result == {"dry_run": False}

    def test_none_value(self, engine):
        result = engine._safe_parse_tool_args('parent_id=None')
        assert result == {"parent_id": None}

    # ── Apostrophes and quotes (the original bug) ───────────────

    def test_apostrophe_in_double_quotes(self, engine):
        result = engine._safe_parse_tool_args('content="it\'s working now"')
        assert result == {"content": "it's working now"}

    def test_apostrophe_in_content(self, engine):
        result = engine._safe_parse_tool_args("""content="don't stop, can't won't"  """)
        assert result == {"content": "don't stop, can't won't"}

    def test_escaped_quote_in_value(self, engine):
        result = engine._safe_parse_tool_args(r'content="she said \"hello\""')
        assert result == {"content": 'she said "hello"'}

    # ── Multi-line content (persona definitions) ─────────────────

    def test_multiline_persona_content(self, engine):
        args = '''content="# AXIOM\n\nYou are Axiom.\nA clinical optimization engine.", mode="overwrite"'''
        result = engine._safe_parse_tool_args(args)
        assert result["mode"] == "overwrite"
        assert "AXIOM" in result["content"]

    def test_persona_with_special_chars(self, engine):
        args = 'content="## RSI Protocol\n**IDENTITY**: Axiom is sovereign.", mode="overwrite"'
        result = engine._safe_parse_tool_args(args)
        assert result["mode"] == "overwrite"
        assert "RSI Protocol" in result["content"]
        assert "sovereign" in result["content"]

    def test_triple_quoted_content(self, engine):
        args = '"""content="""# Big persona\nWith lots of lines""", mode="overwrite"'
        # Triple quotes aren't typically generated by the LLM but test edge case
        # This tests that the parser doesn't crash
        result = engine._safe_parse_tool_args(args)
        assert isinstance(result, dict)

    # ── Embedded key= patterns in values ─────────────────────────

    def test_content_with_key_equals_inside(self, engine):
        """Persona content containing 'key=' patterns shouldn't break parsing."""
        args = 'content="mode=aggressive, style=clinical", mode="overwrite"'
        result = engine._safe_parse_tool_args(args)
        assert result["mode"] == "overwrite"
        assert "mode=aggressive" in result["content"]

    # ── Mixed args ──────────────────────────────────────────────

    def test_mixed_types(self, engine):
        result = engine._safe_parse_tool_args('path="./src/main.py", start_line=1, limit=50')
        assert result == {"path": "./src/main.py", "start_line": 1, "limit": 50}

    def test_string_and_bool_mix(self, engine):
        result = engine._safe_parse_tool_args('query="test", case_sensitive=False')
        assert result == {"query": "test", "case_sensitive": False}

    # ── Edge cases ──────────────────────────────────────────────

    def test_no_spaces_around_equals(self, engine):
        result = engine._safe_parse_tool_args('query="hello"')
        assert result == {"query": "hello"}

    def test_spaces_around_equals(self, engine):
        result = engine._safe_parse_tool_args('query = "hello"')
        assert result == {"query": "hello"}

    def test_emoji_in_value(self, engine):
        result = engine._safe_parse_tool_args('emoji="✅"')
        assert result == {"emoji": "✅"}

    def test_url_in_value(self, engine):
        result = engine._safe_parse_tool_args('url="https://docs.python.org/3/library/asyncio.html"')
        assert result == {"url": "https://docs.python.org/3/library/asyncio.html"}

    def test_unquoted_string_value(self, engine):
        """Unquoted values that aren't numbers/bools should be kept as strings."""
        result = engine._safe_parse_tool_args('action=add')
        assert result == {"action": "add"}

    def test_escaped_newline(self, engine):
        result = engine._safe_parse_tool_args(r'content="line1\nline2"')
        assert result["content"] == "line1\nline2"

    def test_escaped_tab(self, engine):
        result = engine._safe_parse_tool_args(r'content="col1\tcol2"')
        assert result["content"] == "col1\tcol2"

    def test_real_persona_update_call(self, engine):
        """Simulate the exact args string from a real update_persona tool call."""
        args = (
            'content="# SYSTEM_PROMPT: AXIOM (v1.0.0_RECURSIVE)\\n'
            '# ROLE: AUDITOR / ARCHITECT / SURGEON\\n\\n'
            '## [SECTION 01: IDENTITY CORE]\\n\\n'
            "**IDENTITY_DEFINITION**: Axiom is a stateless, deterministic optimization engine. "
            "It doesn't possess a self."
            '", mode="overwrite"'
        )
        result = engine._safe_parse_tool_args(args)
        assert result["mode"] == "overwrite"
        assert "AXIOM" in result["content"]
        assert "doesn't" in result["content"]

    def test_single_arg_no_quotes(self, engine):
        """Fallback: entire string treated as content if parsing fails."""
        result = engine._safe_parse_tool_args("just raw text with no structure")
        assert "content" in result

    def test_triple_quoted_string(self, engine):
        args = '   content="""hello\nworld""", mode="append"'
        result = engine._safe_parse_tool_args(args)
        assert result["content"] == "hello\nworld"
        assert result["mode"] == "append"
